Ext.regModel("app.model.CourseModel",{
    fields:[{
        name:'id',
        type:'int'
    },{
        name:'name',
        type:'string'
    },{
        name:'capacity',
        type:'int'
    },{
        name:'teacherID',
        type:'int'
    },{
        name:'semesterID',
        type:'int'
    },{
        name:'schedule',
        type:'string'
    },{
        name:'credit',
        type:'int'
    },{
        name:'url',
        type:'string'
    },{
        name:'location',
        type:'string'
    },{
        name:'courseType',
        type:'string'
    },{
        name:'evaluationRule',
        type:'int'
    },{
        name:'version',
        type:'int'
    },{
        name:'rule',
        type:'string'
    }]
});
